# App Constants
SEQUENCE_LENGTH = 50
N_FEATURES = 6
CONFIDENCE_THRESHOLD = 0.7

# Sensor Thresholds
ACCEL_Z_DROP_THRESHOLD = -2.5
ACCEL_Z_RISE_THRESHOLD = 3.0
GYRO_THRESHOLD = 1.5

# Detection Parameters
DETECTION_COOLDOWN = 2.0  # seconds
LOCATION_DISTANCE_THRESHOLD = 0.00005  # ~5 meters
